# Generated by Django 3.2.13 on 2023-02-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='grade',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
