# Generated by Django 3.2.13 on 2023-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_designation_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
