# Generated by Django 3.2.13 on 2023-02-17 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_management', '0005_alter_city_name'),
        ('user_management', '0005_auto_20230216_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='designation', to='user_management.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(default=1, max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='Contact number field should only contain digits')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='Contact number field should only contain digits')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='ah', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Name field should not contain special characters')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', message='Name field should not contain special characters')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='area_management.region'),
            preserve_default=False,
        ),
    ]
