# Generated by Django 3.2.13 on 2023-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_features_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='path',
            field=models.CharField(max_length=50),
        ),
    ]
