# Generated by Django 3.2.13 on 2023-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_user_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
