# Generated by Django 3.2.13 on 2023-02-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_user_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reports_to',
        ),
        migrations.AddField(
            model_name='employee',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managing', to='user_management.employee'),
        ),
    ]
