# Generated by Django 3.2.13 on 2023-02-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0008_alter_channel_name'),
        ('user_management', '0011_auto_20230223_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='channel_management.outlet'),
        ),
    ]
