# Generated by Django 3.2.13 on 2023-03-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_employee_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='grade',
        ),
    ]
