# Generated by Django 3.2.13 on 2023-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_alter_usergroup_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', 'f')), fields=('prefix', 'number'), name='unique_grade'),
        ),
    ]
