# Generated by Django 3.2.13 on 2023-03-28 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='additional_contact_information',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_work_days',
            field=models.CharField(blank=True, choices=[('1', 'Monday - Friday'), ('2', 'Monday - Saturday'), ('3', 'Monday - Sunday')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', message='Name field should not contain special characters')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('I', 'Internal'), ('E', 'External')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='end_time_for_corresponding_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_time_for_corresponding_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_days',
            field=models.CharField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
