# Generated by Django 3.2.13 on 2023-03-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_auto_20230321_1011'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique_grade',
        ),
    ]
