# Generated by Django 3.2.13 on 2023-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_remove_grade_unique_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='features',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rolefeatureassociation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='token',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userpasswordhistory',
            name='is_active',
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='permissions',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='rolefeatureassociation',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='userpasswordhistory',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', 'f')), fields=('prefix', 'number'), name='unique_grade'),
        ),
    ]
