# Generated by Django 3.2.13 on 2023-03-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_auto_20230328_0942'),
        ('user_management', '0025_auto_20230327_0648'),
    ]

    operations = [
    ]
