# Generated by Django 3.2.13 on 2023-03-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0026_merge_0022_auto_20230328_0942_0025_auto_20230327_0648'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique_grade',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='end_time_for_corresponding_day',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='start_time_for_corresponding_day',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='additional_contact_information',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='default_work_days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_days',
        ),
    ]
