# Generated by Django 3.2.13 on 2023-03-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0027_auto_20230329_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
    ]
