# Generated by Django 3.2.13 on 2023-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0028_remove_employee_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
