# Generated by Django 3.2.13 on 2023-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0029_employee_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
    ]
