# Generated by Django 3.2.13 on 2023-05-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0035_additionaldatafields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalDataFields',
        ),
    ]
