# Generated by Django 3.2.13 on 2023-06-02 09:39

import django.core.validators
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0036_delete_additionaldatafields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', message='Name field should not contain special characters')])),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('financial_period_start_date', models.DateTimeField(blank=True, null=True)),
                ('financial_period_end_date', models.DateTimeField(blank=True, null=True)),
                ('reporting_currency', models.TextField(blank=True, max_length=1000, null=True)),
                ('operating_currency', models.TextField(blank=True, max_length=1000, null=True)),
                ('days_of_week', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=list, max_length=250, null=True, size=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
