# Generated by Django 3.2.13 on 2023-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0037_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='financial_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='financial_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
