# Generated by Django 3.2.13 on 2023-06-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0038_auto_20230602_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='outlet',
        ),
    ]
