# Generated by Django 3.2.13 on 2023-06-05 06:22

from django.db import migrations, models

from user_management.models import Currency
import json


def add_currencies(apps, schema_editor):
    try:
        with open('user_management/migrations/currencies.json', 'r') as f:
            currency_data = json.load(f)
            for currencies in currency_data["currencies"]:
                Currency.objects.create(code=currencies['code'], name=currencies['name'])
    except Exception as e:
        print(e)


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0039_remove_user_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active',
                 models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE',
                                  max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_currencies),
    ]
