# Generated by Django 3.2.13 on 2023-06-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0040_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='operating_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='operating_company', to='user_management.currency'),
        ),
        migrations.AlterField(
            model_name='company',
            name='reporting_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='reporting_company', to='user_management.currency'),
        ),

    ]
