# Generated by Django 3.2.13 on 2023-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0042_auto_20230605_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='company',
            name='days_of_week',
            field=models.ManyToManyField(related_name='working_days', to='user_management.Weekday'),
        ),
        migrations.AddField(
            model_name='employee',
            name='days_of_week',
            field=models.ManyToManyField(related_name='employee_working_days', to='user_management.Weekday'),
        ),

    ]
