# Generated by Django 3.2.13 on 2023-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0043_auto_20230609_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
