# Generated by Django 3.2.13 on 2023-06-09 11:32

from django.db import migrations, models
from user_management.models import Weekday


def add_weekdays(apps, schema_editor):
    try:
        days = [
            ('Monday', "Mon"),
            ('Tuesday', "Tue"),
            ('Wednesday', "Wed"),
            ('Thursday', "Thu"),
            ('Friday', "Fri"),
            ('Saturday', "Sat"),
            ('Sunday', "Sun")
                ]
        for day in days:
            Weekday.objects.create(name=day[0], code=day[1])
    except Exception as e:
        print(e)


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0044_weekday_code'),
    ]

    operations = [
        migrations.RunPython(add_weekdays),
    ]
