# Generated by Django 3.2.13 on 2023-06-19 13:04

from django.db import migrations, models
from user_management.models import Company


class Migration(migrations.Migration):

    def populate_country_data(self, schema_editor):
        Company.objects.create(name="Lucky Cement Ltd")

    dependencies = [
        ('user_management', '0046_auto_20230619_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_country_data),
    ]
