# Generated by Django 3.2.13 on 2023-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0050_auto_20230624_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='company_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
