# Generated by Django 3.2.13 on 2023-02-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('area_management', '0001_initial'),
        ('market_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('bag', 'bag'), ('loose', 'loose')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('type', models.TextField(blank=True, choices=[('internal', 'internal'), ('external', 'external')],
                                          max_length=1000, null=True)),
                ('weight', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='product_manufacturer',
                                                   to='market_intelligence.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pic_name', models.CharField(max_length=50)),
                ('pic_phone_number', models.CharField(max_length=50)),
                ('pic_email', models.CharField(max_length=50)),
                ('items_capacity', models.CharField(max_length=50)),
                ('warehouse_square_footage', models.CharField(max_length=50)),
                ('storage_types', models.CharField(max_length=50)),
                ('loading_unloading_info', models.CharField(max_length=50)),
                ('operating_hours', models.CharField(max_length=50)),
                ('sap_id', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('additional_information', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('IL', 'Internal'), ('EL', 'External')], max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_city',
                                           to='area_management.city')),
                ('product',
                 models.ManyToManyField(related_name='warehouse_products', to='inventory_management.Product')),
                ('region',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_region',
                                   to='area_management.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_zone',
                                           to='area_management.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('sap_code', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_city',
                                           to='area_management.city')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_region',
                                             to='area_management.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
