# Generated by Django 3.2.13 on 2023-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='additional_information',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='loading_unloading_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='sap_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='storage_types',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_square_footage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
