# Generated by Django 3.2.13 on 2023-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='type',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IL', 'Internal'), ('EL', 'External')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.TextField(blank=True, choices=[('bag', 'bag'), ('loose', 'loose')], max_length=1000, null=True),
        ),
    ]
