# Generated by Django 3.2.13 on 2023-02-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_management', '0005_alter_city_name'),
        ('market_intelligence', '0006_auto_20230221_1702'),
        ('user_management', '0010_alter_user_is_locked'),
        ('inventory_management', '0010_auto_20230220_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='pic_email',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='pic_name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='pic_phone_number',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='person_in_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse', to='user_management.employee'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='area_management.region'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturer', to='market_intelligence.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.TextField(choices=[('bag', 'bag'), ('loose', 'loose')], default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
