# Generated by Django 3.2.13 on 2023-02-23 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20230223_0647'),
        ('inventory_management', '0011_auto_20230223_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='pic_email',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic_phone_number',
        ),
        migrations.AddField(
            model_name='plant',
            name='person_in_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plant', to='user_management.employee'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', message='Name field should not contain special characters')]),
        ),
    ]
