# Generated by Django 3.2.13 on 2023-02-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0012_auto_20230223_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='manufacturing_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
