# Generated by Django 3.2.13 on 2023-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0014_alter_warehouse_items_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
