# Generated by Django 3.2.13 on 2023-03-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0015_auto_20230320_1151'),
        ('inventory_management', '0015_auto_20230321_1011'),
    ]

    operations = [
    ]
