# Generated by Django 3.2.13 on 2023-03-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('inventory_management', '0016_merge_0015_auto_20230320_1151_0015_auto_20230321_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product',
                                    to='inventory_management.producttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
