# Generated by Django 3.2.13 on 2023-03-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0017_auto_20230322_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
    ]
