# Generated by Django 3.2.13 on 2023-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0021_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=[('KGs', 'KGs'), ('BAGS', 'BAGS'), ('TONS', 'TONS')], default="KGs", max_length=30),
            preserve_default=False,
        ),
    ]
