# Generated by Django 3.2.13 on 2023-02-16 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_management', '0004_auto_20230216_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Name field should not contain special characters')]),
        ),
    ]
