# Generated by Django 3.2.13 on 2023-05-23 07:32

from django.db import migrations, models
import django.db.models.deletion
import json
from area_management.models import Country


class Migration(migrations.Migration):
    dependencies = [
        ('area_management', '0007_auto_20230314_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE',
                                   max_length=8),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE',
                                   max_length=8),
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE',
                                   max_length=8),
        ),
        migrations.AddField(
            model_name='subzone',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE',
                                   max_length=8),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_active',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE',
                                   max_length=8),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region',
                                    to='area_management.country'),
            preserve_default=False,
        ),
    ]
