# Generated by Django 3.2.13 on 2023-02-28 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_logs', '0002_auto_20230228_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='after',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='before',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='operation',
            field=models.CharField(blank=True, choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('LOGIN', 'LOGIN')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to=settings.AUTH_USER_MODEL),
        ),
    ]
