# Generated by Django 3.2.13 on 2023-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0003_auto_20230228_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
