# Generated by Django 3.2.13 on 2023-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0004_auditlogs_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlogs',
            name='is_active',
        ),
        migrations.AddField(
            model_name='auditlogs',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=8),
        ),
    ]
