# Generated by Django 3.2.13 on 2023-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0006_rename_status_auditlogs_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='object',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
