# Generated by Django 3.2.13 on 2023-07-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0007_alter_auditlogs_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlogs',
            name='after',
        ),
        migrations.RemoveField(
            model_name='auditlogs',
            name='before',
        ),
        migrations.AddField(
            model_name='auditlogs',
            name='changes',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
