# Generated by Django 3.2.13 on 2023-07-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0008_auto_20230710_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
