# Generated by Django 3.2.13 on 2023-02-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0003_auto_20230216_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='owner_cnic',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
