# Generated by Django 3.2.13 on 2023-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0004_alter_outlet_owner_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='email',
            field=models.EmailField(blank=True, max_length=35, null=True),
        ),
    ]
