# Generated by Django 3.2.13 on 2023-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0005_alter_outlet_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='category',
            field=models.CharField(choices=[('IL', 'Internal'), ('EL', 'External')], default='IL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outlet',
            name='owner_cnic',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
