# Generated by Django 3.2.13 on 2023-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0006_auto_20230216_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='owner_name',
            field=models.CharField(default='hamza', max_length=100),
            preserve_default=False,
        ),
    ]
