# Generated by Django 3.2.13 on 2023-02-16 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0007_alter_outlet_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Name field should not contain special characters')]),
        ),
    ]
