# Generated by Django 3.2.13 on 2023-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0009_auto_20230228_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
