# Generated by Django 3.2.13 on 2023-06-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0015_auto_20230603_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='distributor',
            field=models.ManyToManyField(blank=True, null=True, related_name='managing_outlets', to='channel_management.Outlet'),
        ),
    ]
