# Generated by Django 3.2.13 on 2023-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0016_alter_outlet_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='distributor',
            field=models.ManyToManyField(blank=True, null=True, related_name='_channel_management_outlet_distributor_+', to='channel_management.Outlet'),
        ),
    ]
