# Generated by Django 3.2.13 on 2023-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_management', '0019_alter_outlet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='owner_cnic',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
