# Generated by Django 3.2.13 on 2023-02-16 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('subject', models.TextField(max_length=100)),
                ('body', models.TextField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('recipient_groups', models.ManyToManyField(blank=True, null=True, related_name='emails', to='user_management.Role')),
                ('recipient_list', models.ManyToManyField(blank=True, null=True, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
