# Generated by Django 3.2.13 on 2023-02-21 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0010_alter_user_is_locked'),
        ('notifications_management', '0003_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='recipient_groups',
            field=models.ManyToManyField(related_name='emails_recipient_groups', to='user_management.Role'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='recipient_list',
            field=models.ManyToManyField(related_name='emails_recipient_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
