# Generated by Django 3.2.13 on 2023-03-14 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_usergroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications_management', '0004_auto_20230221_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='recipient_groups',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='recipient_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='emails_recipient_groups', to='user_management.UserGroup'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='recipient_roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='emails_recipient_roles', to='user_management.Role'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='recipient_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='emails_recipient_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
