# Generated by Django 3.2.13 on 2023-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_management', '0005_auto_20230314_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
