# Generated by Django 3.2.13 on 2023-03-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_management', '0006_emailtemplate_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='is_active',
        ),
    ]
