# Generated by Django 3.2.13 on 2023-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_management', '0008_emailtemplate_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='status',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
