# Generated by Django 3.2.13 on 2023-07-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_management', '0011_emailtemplate_notification_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(max_length=500),
        ),
    ]
