# Generated by Django 3.2.13 on 2023-02-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='name',
        ),
    ]
