# Generated by Django 3.2.13 on 2023-03-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_intelligence', '0009_auto_20230327_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='market_intelligence.brandtype'),
            preserve_default=False,
        ),
    ]
