# Generated by Django 3.2.13 on 2023-03-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_intelligence', '0010_brand_brand_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='brandtype',
            old_name='status',
            new_name='is_active',
        ),
    ]
