# Generated by Django 3.2.13 on 2023-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_intelligence', '0011_auto_20230327_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandtype',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand_type', to='area_management.Region'),
        ),
    ]
