# Generated by Django 3.2.13 on 2023-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_management', '0009_auto_20230623_0652'),
        ('market_intelligence', '0012_brandtype_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandtype',
            name='region',
            field=models.ManyToManyField(related_name='brand_type', to='area_management.Region'),
        ),
    ]
